// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbzuocsgfkugpsahesay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFienVvY3NnZmt1Z3BzYWhlc2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTY4OTQsImV4cCI6MjA1NjkzMjg5NH0.iiniIG_DjRQWMS6ySf3kCp3BPWgdm3cw1Xx6oAwzJrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);